### ISSUE TITLE
Mudar o título da página

### ISSUE THREAD

**Issue by diogomoreira** [ads-ifpb-gcm/vem-pra-ads-fabricaMonstrosGit#1]
Na parte superior da página, é mostrado a mensagem "Hi! I'm Prologue, a free responsive site template designed by HTML5 UP." quando deveria mostrar o nome "Vem para ADS"

**Comment by AlissonAlmeidaSS** [comment]
Deveria ter uma ! no final

**Comment by DionesGomes** [comment]
Olá, amigos!

**Comment by LuanB007** [comment]
Palmeiras não tem Mundial!

**Comment by rogerioalcantaracz** [comment]
Falta o ponto de EXCLAMAÇÃO!

**Comment by diogomoreira** [comment]
Consertado!
