### ISSUE TITLE
Adicionar email da coordenação

### ISSUE THREAD

**Issue by diogomoreira** [ads-ifpb-gcm/vem-pra-ads-fabricaMonstrosGit#2]
Na página de contato, deveria ter o email da coordenação, que é repassado para todos os coordenadores.
O email é: **cads.cz@ifpb.edu.br**

**Comment by FlavioHenriique** [comment]
Entendido!

**Comment by lucasduete** [comment]
Como já fechamos a v1.0 e já estamos trabalhando na v1.1 suponho que seja melhor modificar a milestone para a v1.1

**Comment by lucasduete** [comment]
Remanejando para milestone v1.1

**Comment by lucasduete** [comment]
O email foi adicionado como foi requisitado, deixei o email que já estava na página.
