### ISSUE TITLE
Pagina sobre campus IFPB CZ

### ISSUE THREAD

**Issue by lucasduete** [ads-ifpb-gcm/vem-pra-ads-fabricaMonstrosGit#5]
acho que é necessário adicionar mais fotos do campus, segue abaixo algumas 
[img1](https://www.google.com.br/imgres?imgurl=http%3A%2F%2Fwww.guiadoturismobrasil.com%2Fup%2Fimg%2F1446824040.jpg&imgrefurl=http%3A%2F%2Fwww.guiadoturismobrasil.com%2Fcidade%2FPB%2F592%2Fcajazeiras&docid=zD6qavYy9DllXM&tbnid=wdb2iJO4RMbhIM%3A&vet=10ahUKEwiR-8OIurHTAhVBEZAKHd63BXgQMwhcKBowGg..i&w=1200&h=800&safe=off&bih=678&biw=1309&q=cajazeiras&ved=0ahUKEwiR-8OIurHTAhVBEZAKHd63BXgQMwhcKBowGg&iact=mrc&uact=8
)
[img2](https://www.google.com.br/imgres?imgurl=https%3A%2F%2Feditor.ifpb.edu.br%2Fcampi%2Fcajazeiras%2Fcampus-de-cajazeiras-1%2Farquivos%2Fimagens%2FDSC06508.1.JPG%2Fimage_preview&imgrefurl=https%3A%2F%2Feditor.ifpb.edu.br%2Fcampi%2Fcajazeiras&docid=dOW8Fqd-G8N1TM&tbnid=G8saqqYgYIvGyM%3A&vet=10ahUKEwiR-8OIurHTAhVBEZAKHd63BXgQMwh_KD0wPQ..i&w=400&h=300&safe=off&bih=678&biw=1309&q=cajazeiras&ved=0ahUKEwiR-8OIurHTAhVBEZAKHd63BXgQMwh_KD0wPQ&iact=mrc&uact=8)
[img3](https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fcoisasdecajazeiras.com.br%2Fwp-content%2Fuploads%2F2014%2F02%2FIfpb-01.jpg&imgrefurl=https%3A%2F%2Fcoisasdecajazeiras.com.br%2Finscricoes-abertas-para-professor-substituto-do-campus-do-ifpb-em-cajazeiras%2F&docid=YxLbp1XWQi6uTM&tbnid=usQzCz8hBU-yoM%3A&vet=10ahUKEwjx-v6vurHTAhXDl5AKHZkwAHg4ZBAzCAUoAzAD..i&w=620&h=322&safe=off&bih=678&biw=1309&q=cajazeiras&ved=0ahUKEwjx-v6vurHTAhXDl5AKHZkwAHg4ZBAzCAUoAzAD&iact=mrc&uact=8)

**Comment by lucasduete** [comment]
usa esse codigo pra colocar as imagens, vai ficar igual a pagina de informações sobre cajazeiras : 

> <div class="row">
								<div class="4u 12u$(mobile)">
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic02.jpg" alt="" /></a>
										<header>
											<h3>Ipsum Feugiat</h3>
										</header>
									</article>
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic03.jpg" alt="" /></a>
										<header>
											<h3>Rhoncus Semper</h3>
										</header>
									</article>
								</div>
								<div class="4u 12u$(mobile)">
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic04.jpg" alt="" /></a>
										<header>
											<h3>Magna Nullam</h3>
										</header>
									</article>
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic05.jpg" alt="" /></a>
										<header>
											<h3>Natoque Vitae</h3>
										</header>
									</article>
								</div>
								<div class="4u$ 12u$(mobile)">
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic06.jpg" alt="" /></a>
										<header>
											<h3>Dolor Penatibus</h3>
										</header>
									</article>
									<article class="item">
										<a href="#" class="image fit"><img src="images/pic07.jpg" alt="" /></a>
										<header>
											<h3>Orci Convallis</h3>
										</header>
									</article>
								</div>
							</div>

**Comment by FlavioHenriique** [comment]
Foram adicionadas duas imagens para a página.
