### ISSUE TITLE
Construção da Página de Oportunidades para o Aluno

### ISSUE THREAD

**Issue by lucasduete** [ads-ifpb-gcm/vem-pra-ads-fabricaMonstrosGit#6]
Falta apenas a contrução da pagina de oportunidades para o aluno, necessita-se dos seguintes tópicos : 

- Falar de maneira breve sobre: Extensão, Pesquisa
- Alunos egressos e onde estão trabalhando (Pode ser só a cidade)
- Alunos egressos que fizeram mestrado/doutorado

**Comment by alissonxrx** [comment]
Tudo certo cuidarei dessa parte

**Comment by lucasduete** [comment]
Informações cedidas por Diogo :v: :+1: 

Na parte de pesquisa e extensão, pode colocar só uma breve descrição sobre o que é Pesquisa e Extensão, o que você poderia encontrar no Wikipedia mesmo. Talvez o ultimo edital que foi aberto seria bacana também.
Os ultimos editais de pesquisa estão aqui: http://www.ifpb.edu.br/prpipg/editais
Os últimos editais de extensão estão aqui: http://www.ifpb.edu.br/proexc/editais/extensao

Quanto aos alunos que estão trabalhando, caso você não conheça nenhum, pode colocar só a lista das empresas que já tivemos/temos ex-alunos trabalhando.
EBIX, CAST Tecnologia, BRQ, Trana, Indra Company, Phoebus Tecnologia, Accenture, Stefanini, Dynavideo, Digivox, Ruppells Griffon (Austrália), Instituto Federal da Paraíba (IFPB), Instituto Federal de Pernambuco (IFPE), UEPB, UFC

Quanto ao mestrado, nossos alunos já estiveram em:
UFPB, UFCG e C.E.S.AR.

**Comment by lucasduete** [comment]
Issue completo pelo commit 72984f6
